// ignore_for_file: public_member_api_docs, sort_constructors_first
import 'dart:async';
import 'dart:convert';
import 'dart:developer';

import 'package:http/http.dart';
import 'package:rest_countries_api_implementation/countryMetaData_model.dart';

extension on Response {
  bool get isSuccess => statusCode == 200;
}

abstract class ApiServices {
  String get baseUrl => "https://restcountries.com/v3.1";
  String get apiUrl;
  dynamic fetch({String endPoint = ""}) async {
    log('[URL : ${baseUrl + apiUrl + endPoint}]');
    var response = await get(Uri.parse(baseUrl + apiUrl + endPoint));
    log('Response : ${response.body}');
    if (response.isSuccess) {
      log('[Reached]');
      return jsonDecode(response.body);
    }
    return null;
  }
}

class CountryApiService extends ApiServices {
  @override
  String get apiUrl => "/name";

  Future<List<Autogenerated>> fetchCountriesData(String countryName) async {
    List countryData = await fetch(endPoint: countryName);
    return countryData.map((map) {
      return Autogenerated.fromMap(map);
    }).toList();
  }
}
